### ISSUE TITLE
TypeError: t.SpringValue is not a constructor when using create-react-app

### ISSUE THREAD

**Issue by justfeelingscrafts** [choozn/react-parallax-mouse#36] opened 2024-02-08 00:10 UTC
**Describe the bug**

After installing the package and adding the example code

import { MouseParallaxContainer, MouseParallaxChild } from "react-parallax-mouse";
<MouseParallaxContainer globalFactorX={0.1} globalFactorY={0.1}>
  <MouseParallaxChild factorX={0.3} factorY={0.5}>
    <img src="example1.jpg" alt="" /> // I added my image here
  </MouseParallaxChild>
  <MouseParallaxChild factorX={0.7} factorY={0.8}>
    <img src="example2.jpg" alt="" /> // I added my image here
  </MouseParallaxChild>
</MouseParallaxContainer>

I get the following error in the console

Uncaught TypeError: t.SpringValue is not a constructor
    at ./node_modules/react-parallax-mouse/dist/index.js (defaults.ts:5:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/common/mountains.tsx (mountains.styles.ts:36:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/pages/home/home.tsx (home.styles.ts:29:1)
    at options.factory (react refresh:6:1)

I'm using react with typescript

**Comment by choozn** [comment] 2024-02-08 06:15
Hey @justfeelingscrafts, which version of react-parallax-mouse are you using? This bug is already known (#34) and should be fixed in the latest version.

**Comment by kfaherty** [comment] 2024-02-09 16:07
I am also seeing this issue on `2.1.0`

**Comment by choozn** [comment] 2024-02-09 20:22
Well that's a bummer. Sadly I don't really have the time right now to look into this. It seems that this is also an issue with react-spring. Until I find the the time this bug will persist. Sorry in advance for that.

**Comment by choozn** [comment] 2024-03-04 20:12
I was not able to reproduce this bug yet. Are you using `react-spring` in your project outside of `react-parallax-mouse`?
Could you provide me with a minimal repository, showcasing the bug so I can find out where the bug emerges from?

**Comment by wagnero11** [comment] 2024-03-14 14:33
Same over here, created a fresh react-app and installed `react-parallax-mouse`, I do the imports, copy and paste the container & child straight away I get the t.SpringValue error

**Comment by eyooooo** [comment] 2024-03-15 16:35
same here. steps to reproduce are:

1. npx create-react-app
2. npm install react-parallax-mouse
3. add the import import { MouseParallaxContainer, MouseParallaxChild } from "react-parallax-mouse";
4. doesnt work

maybe you're testing on some ancient version of React?

**Comment by ntchungse** [comment] 2024-06-14 07:27
same issue

**Comment by choozn** [comment] 2024-06-21 20:00
I have nailed down the problem in this case. I am still on the search for a fix and will look into the bug in the following days.
For those interested, its an ESM / CommonJS problem with CRA and libraries that depend on CJS libraries.

The relevant issues are the following: https://github.com/facebook/create-react-app/issues/11889, https://github.com/pmndrs/react-spring/issues/2212

**Comment by choozn** [comment] 2024-07-08 13:43
## How to resolve this issue:

- This is an error with `create-react-app`, which uses a version of `react-scripts` that bundles .cjs files wrong. (https://github.com/facebook/create-react-app/issues/11889)
- This bug will continue to exist, as `create-react-app` was __deprecated__ in 2023.

### I want to continue using create-react-app
- ▶ The current fix for this is explained here: 
    - https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114878121 
   - or https://github.com/reduxjs/redux-toolkit/issues/4474#issuecomment-2194397384 
   - or https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114928008.

### I can switch to an alternative
- ▶ __Do that__. Don't use software, that is deprecated since over a year. Alternatives are listed here: https://www.freecodecamp.org/news/how-to-create-a-react-app-in-2024/


## Moral of the story
- Don't use `create-react-app`.

**Closed as completed by choozn** 2024-07-08 13:43 UTC
Labels: bug
